--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/VeinMiner
projects:
  VeinMiner:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - tests
      - .github
    excludeFiles:
      - .php-cs-fixer.php
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
...
