name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: PHPStan analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: pmmp/setup-php-action@247e08acd52c1465f8f144c162c88f079d8c1174
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        working-directory: ./phpstan
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        working-directory: ./phpstan
        run: vendor/bin/phpstan analyze
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.21.2
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.11

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi